# Generated by Django 5.0.14 on 2026-04-17 03:26

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='back_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=users.models.doc_upload_path),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='front_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=users.models.doc_upload_path),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=users.models.doc_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=users.models.avatar_upload_path),
        ),
    ]
