# Generated by Django 5.0.14 on 2026-04-01 19:51

import chat.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('👍', 'Gosto'), ('👎', 'Não gosto'), ('😂', 'Engraçado'), ('😮', 'Surpresa'), ('❤️', 'Coração'), ('🤝', 'Acordo')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reacção',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leitura de mensagem',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('direct', 'Conversa directa'), ('offer', 'Ligada a uma oferta')], default='direct', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('closed', 'Fechada'), ('archived', 'Arquivada'), ('blocked', 'Bloqueada')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('room_created', 'Sala criada'), ('member_joined', 'Membro entrou'), ('member_left', 'Membro saiu'), ('room_closed', 'Sala fechada'), ('room_blocked', 'Sala bloqueada'), ('deal_proposed', 'Acordo proposto'), ('deal_accepted', 'Acordo aceite'), ('deal_cancelled', 'Acordo cancelado')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento de sala',
                'verbose_name_plural': 'Eventos de sala',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membro da sala',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msg_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('file', 'Ficheiro'), ('system', 'Evento do sistema')], default='text', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=chat.models.message_file_upload_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
    ]
