# Generated by Django 5.0.14 on 2026-04-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
