# Generated by Django 5.0.14 on 2026-04-01 19:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=10)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Moeda',
                'verbose_name_plural': 'Moedas',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OfferInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Aguardando resposta'), ('accepted', 'Aceite'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado pelo interessado'), ('chat_open', 'Chat aberto')], default='pending', max_length=12)),
                ('message', models.TextField(blank=True, help_text='Mensagem opcional do interessado ao vendedor.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interesse em oferta',
                'verbose_name_plural': 'Interesses em ofertas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visualização de oferta',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=24)),
                ('source', models.CharField(default='api', max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_base', to='offers.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_quote', to='offers.currency')),
            ],
            options={
                'verbose_name': 'Taxa de câmbio',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('give_amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('want_amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=8, help_text='Taxa de câmbio real no momento da publicação.', max_digits=24)),
                ('implied_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('offer_type', models.CharField(choices=[('sell', 'Vender'), ('buy', 'Comprar')], default='sell', max_length=4)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('dealing', 'Em negócio'), ('closed', 'Fechada'), ('expired', 'Expirada')], default='active', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Observações visíveis a outros utilizadores.', max_length=500)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('give_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_give', to='offers.currency')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
