# Generated by Django 5.0.14 on 2026-04-01 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='want_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers_want', to='offers.currency'),
        ),
        migrations.AddField(
            model_name='offerinterest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offerinterest',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='offerinterest',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_interest', to='chat.room'),
        ),
        migrations.AddField(
            model_name='offerview',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='offerview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('from_currency', 'to_currency')},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'give_currency', 'want_currency'], name='offers_offe_status_c2ba16_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['owner', 'status'], name='offers_offe_owner_i_812830_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['created_at'], name='offers_offe_created_968b40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerinterest',
            unique_together={('offer', 'buyer')},
        ),
        migrations.AddIndex(
            model_name='offerview',
            index=models.Index(fields=['offer', 'viewed_at'], name='offers_offe_offer_i_452c03_idx'),
        ),
    ]
