# Generated by Django 5.0.14 on 2026-04-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_sender'),
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerinterest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='chat.room'),
        ),
    ]
