# Generated by Django 5.0.14 on 2026-04-01 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('give_amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('want_amount', models.DecimalField(decimal_places=2, max_digits=24)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=24)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('disputed', 'Em disputa')], default='completed', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avaliação',
            },
        ),
    ]
