# Generated by Django 5.0.14 on 2026-04-01 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_interest', 'Novo interesse na tua oferta'), ('interest_accepted', 'O teu interesse foi aceite'), ('interest_rejected', 'O teu interesse foi rejeitado'), ('interest_cancelled', 'Um interessado cancelou'), ('offer_expired', 'A tua oferta expirou'), ('new_message', 'Nova mensagem'), ('deal_accepted', 'Acordo aceite na conversa'), ('deal_cancelled', 'Acordo cancelado'), ('rate_alert', 'Alerta de câmbio'), ('account_verified', 'Conta verificada'), ('account_rejected', 'Verificação rejeitada'), ('system', 'Notificação do sistema')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(max_length=300)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_ws', models.BooleanField(default=False)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_sent_push', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push')], default='in_app', max_length=10)),
                ('new_interest', models.BooleanField(default=True)),
                ('interest_accepted', models.BooleanField(default=True)),
                ('interest_rejected', models.BooleanField(default=True)),
                ('interest_cancelled', models.BooleanField(default=True)),
                ('offer_expired', models.BooleanField(default=True)),
                ('new_message', models.BooleanField(default=True)),
                ('deal_accepted', models.BooleanField(default=True)),
                ('deal_cancelled', models.BooleanField(default=True)),
                ('rate_alert', models.BooleanField(default=False)),
                ('account_verified', models.BooleanField(default=True)),
                ('system', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Preferências de notificação',
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('android', 'Android (FCM)'), ('ios', 'iOS (APNs)'), ('web', 'Web (FCM Web)')], max_length=10)),
                ('token', models.TextField(unique=True)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo Push',
                'verbose_name_plural': 'Dispositivos Push',
            },
        ),
    ]
